name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Configurar entorno
        run: echo "Configurando entorno de compilacion"

      - name: Compilar proyecto
        run: python -m compileall cafe

      - name: Ejecutar pruebas TDD
        run: python -m unittest discover -s tests -v
